# Generated by Django 5.1.2 on 2024-10-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('surname', models.CharField(max_length=35)),
                ('fatherly', models.CharField(max_length=35, null=True)),
                ('grade', models.CharField(max_length=5, null=True)),
                ('occupation', models.CharField(max_length=35)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
