# Generated by Django 5.1.2 on 2024-10-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorization_app', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fatherly',
            field=models.CharField(blank=True, default=False, max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, default=False, max_length=5),
        ),
    ]
